# Generated by Django 5.2.16 on 2026-07-20 11:22

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='项目名称')),
                ('summary', models.TextField(blank=True, verbose_name='项目简介')),
                ('department', models.CharField(choices=[('hardware', '硬件部'), ('software', '软件部'), ('joint', '软硬结合'), ('other', '其他')], default='other', max_length=12, verbose_name='所属方向')),
                ('status', models.CharField(choices=[('active', '进行中'), ('archived', '已归档')], db_index=True, default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目录名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_folders_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectfolder', verbose_name='上级目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目目录',
                'verbose_name_plural': '项目目录',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='显示名')),
                ('file', models.FileField(upload_to=projects.models.project_file_path, verbose_name='文件')),
                ('size', models.BigIntegerField(default=0, editable=False, verbose_name='大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='项目')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projectfolder', verbose_name='所在目录')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', '负责人'), ('member', '成员')], default='member', max_length=8, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'ordering': ['role', 'joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectfolder',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='uniq_folder_in_parent'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member'),
        ),
    ]
