# Generated by Django 5.2.17 on 2026-08-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_h', help_text='4:3 横构图。没有封面时作品墙显示空焊盘占位，不会是碎图。', upload_to='works/covers/%Y/%m/', verbose_name='展示封面', width_field='cover_w'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_h',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_w',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='highlight',
            field=models.CharField(blank=True, help_text='作品墙卡片上显示的一行字。留空则截取项目简介。', max_length=120, verbose_name='一句话亮点'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='首页只展示精选的几个。要先「公开到作品墙」才有效。', verbose_name='首页精选'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='默认关闭。打开后这个项目会出现在 /works/ 上，外人可见。', verbose_name='公开到作品墙'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='逗号分隔，例如：STM32, 电赛, PCB。只用于展示，不参与筛选。', max_length=120, verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='ProjectShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='works/shots/%Y/%m/', verbose_name='展示图', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='图注')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='数字小的排前面', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '作品展示图',
                'verbose_name_plural': '作品展示图',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
