# Generated by Django 5.2.17 on 2026-09-06 10:31

import django.core.validators
import django.db.models.deletion
import projects.models
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def preserve_project_years(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.using(schema_editor.connection.alias).only('id', 'created_at').iterator():
        Project.objects.using(schema_editor.connection.alias).filter(pk=project.pk).update(
            work_year=timezone.localtime(project.created_at).year)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_cover_project_cover_h_project_cover_w_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.JSONField(default=dict)),
                ('published', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=projects.models.work_image_path)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='作品链接'),
        ),
        migrations.AddField(
            model_name='project',
            name='importance',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='重要性'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_member_work',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='public_credit',
            field=models.CharField(blank=True, max_length=120, verbose_name='公开署名'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_year',
            field=models.PositiveSmallIntegerField(db_index=True, default=projects.models.current_work_year, verbose_name='作品年份'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('importance__lte', 100)), name='project_importance_range'),
        ),
        migrations.AddField(
            model_name='memberwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberwork',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_work', to='projects.project'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.memberwork'),
        ),
        migrations.RunPython(preserve_project_years, migrations.RunPython.noop),
    ]
