# Generated by Django 5.2.16 on 2026-07-19 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='勋章名称')),
                ('icon', models.CharField(default='🏅', help_text='直接填 emoji（推荐），如 🏅🥇⚡🔧', max_length=40, verbose_name='图标')),
                ('color', models.CharField(default='#f59e0b', max_length=20, verbose_name='颜色')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
            ],
            options={
                'verbose_name': '勋章',
                'verbose_name_plural': '勋章',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='职位名称')),
                ('color', models.CharField(default='#b8860b', help_text='十六进制色值，如 #b8860b', max_length=20, verbose_name='徽章颜色')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='数字小的排前面', verbose_name='排序')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='member_level',
            field=models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '报名会员'), (2, '预备会员'), (3, '正式会员'), (4, '干事'), (5, '管理员')], db_index=True, default=0, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='LevelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '报名会员'), (2, '预备会员'), (3, '正式会员'), (4, '干事'), (5, '管理员')], verbose_name='原等级')),
                ('to_level', models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '报名会员'), (2, '预备会员'), (3, '正式会员'), (4, '干事'), (5, '管理员')], verbose_name='新等级')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_ops', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_logs', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '等级变更记录',
                'verbose_name_plural': '等级变更记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='accounts.position', verbose_name='职位'),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('purpose', models.CharField(choices=[('register', '注册'), ('reset', '找回密码'), ('login', '验证码登录')], max_length=10, verbose_name='用途')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='尝试次数')),
                ('used', models.BooleanField(default=False, verbose_name='已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'used'], name='accounts_ve_email_e54d45_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='授予理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='授予时间')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medals_granted', to=settings.AUTH_USER_MODEL, verbose_name='授予人')),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded', to='accounts.medal', verbose_name='勋章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '成员勋章',
                'verbose_name_plural': '成员勋章',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'medal'), name='uniq_user_medal')],
            },
        ),
    ]
