# Generated by Django 5.2.16 on 2026-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='color',
            field=models.CharField(default='#c98a3d', max_length=20, verbose_name='颜色'),
        ),
    ]
