# Generated by Django 5.2.17 on 2026-08-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_formal_recruitment_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='blurb',
            field=models.CharField(blank=True, help_text='会显示在公开团队页的职位分组下，例如「统筹整体方向与对外联络」', max_length=80, verbose_name='这个职位做什么'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_bio',
            field=models.CharField(blank=True, help_text='会显示在公开团队页上，例如「负责硬件培训，喜欢折腾电源」', max_length=120, verbose_name='一句话介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_on_team',
            field=models.BooleanField(default=False, verbose_name='在公开团队页展示我'),
        ),
    ]
