# Generated by Django 5.2.17 on 2026-09-03 03:17

import accounts.choices
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_applicant_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position_term_start',
            field=models.PositiveSmallIntegerField(blank=True, choices=accounts.choices.position_term_choices, help_text='任期起始年份，与入学年级无关；历史不明时留空。', null=True, verbose_name='任职届次'),
        ),
        migrations.CreateModel(
            name='PositionAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=30, verbose_name='职位名称快照')),
                ('term_start', models.PositiveSmallIntegerField(blank=True, choices=accounts.choices.position_term_choices, null=True, verbose_name='任职届次')),
                ('started_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='登记时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_appointments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '任职记录',
                'verbose_name_plural': '任职记录',
                'ordering': ['-term_start', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='one_current_position_per_user')],
            },
        ),
    ]
