# Generated by Django 5.2.17 on 2026-09-03 07:42

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_position_appointments'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.MemberManager()),
            ],
        ),
    ]
