# Generated by Django 5.2.16 on 2026-07-20 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('category', models.CharField(choices=[('notice', '通知公告'), ('activity', '协会动态'), ('honor', '获奖喜报')], default='notice', max_length=12, verbose_name='栏目')),
                ('cover', models.ImageField(blank=True, help_text='选填，列表页与详情页顶部展示', upload_to='news/covers/%Y/', verbose_name='封面图')),
                ('body', models.TextField(help_text='支持 Markdown：标题、加粗、列表、表格、图片、链接等', verbose_name='正文（Markdown）')),
                ('min_level', models.PositiveSmallIntegerField(choices=[(0, '公开（所有人）'), (1, '报名会员及以上'), (2, '预备会员及以上'), (3, '正式会员及以上'), (4, '干事及以上')], default=0, help_text='达到该等级的成员才能看到这篇公告', verbose_name='可见等级')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_published', models.BooleanField(default=True, help_text='取消勾选即下架（仅驾驶舱可见）', verbose_name='已发布')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发布时间')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-pinned', '-published_at'],
            },
        ),
    ]
