# Generated by Django 5.2.17 on 2026-08-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_formal_member_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='例如：全国大学生电子设计竞赛 一等奖', max_length=120, verbose_name='奖项')),
                ('contest', models.CharField(blank=True, help_text='例如：电赛、蓝桥杯。留空则不显示', max_length=80, verbose_name='赛事')),
                ('level', models.PositiveSmallIntegerField(choices=[(30, '国家级'), (20, '省级'), (10, '校级'), (5, '其他')], db_index=True, default=10, verbose_name='等级')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='年份')),
                ('awardee', models.CharField(blank=True, max_length=120, verbose_name='获奖人 / 队伍')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='补充说明')),
                ('certificate', models.ImageField(blank=True, height_field='cert_h', help_text='选填。有照片的会额外出现在荣誉墙顶部的证书条带里。', upload_to='honors/%Y/%m/', verbose_name='证书照片', width_field='cert_w')),
                ('cert_w', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('cert_h', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='公开')),
                ('is_featured', models.BooleanField(default=False, help_text='首页只列几项。要先「公开」才有效。', verbose_name='首页展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('post', models.ForeignKey(blank=True, help_text='选填。填了荣誉墙上这一项就能点进完整的喜报。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honors', to='news.post', verbose_name='对应喜报')),
            ],
            options={
                'verbose_name': '荣誉',
                'verbose_name_plural': '荣誉',
                'ordering': ['-year', '-level', 'title'],
            },
        ),
    ]
