# Generated by Django 5.2.17 on 2026-08-31 15:03
#
# 只动 help_text，数据库层面是空操作（CharField 的长度与约束一个字都没变）。
# 但 Django 的 `makemigrations --check` 认状态、不认「反正 SQL 一样」——
# 不把它记下来的话 preflight 第 2 项会一直红，而下一次真的改模型时这条会被
# 顺手捎带进去，届时谁都说不清那次迁移到底改了什么。
#
# help_text 会出现在驾驶舱录入表单上，所以它不是纯注释：那句话是给站务看的
# 「这个字段会公开渲染，考证过程别写这儿」。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_honor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='note',
            field=models.CharField(blank=True, help_text='**会显示在公开页面上**，只写给访客看的话（届次、作品名、指导教师、证书编号）。「这张照片是从哪来的、为什么没有证书图」这类考证过程写进 docs/，不要写在这里 —— 这个字段不过 Markdown，写了 ** 会原样印出来。', max_length=200, verbose_name='补充说明'),
        ),
    ]
