# Generated by Django 5.2.17 on 2026-09-06 12:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_honor_note'),
        ('projects', '0003_member_work_publishing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honor',
            options={'ordering': ['-year', '-importance', '-level', 'title', 'pk'], 'verbose_name': '荣誉', 'verbose_name_plural': '荣誉'},
        ),
        migrations.AddField(
            model_name='honor',
            name='importance',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='重要性'),
        ),
        migrations.AddField(
            model_name='honor',
            name='is_member_honor',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='honor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honors', to='projects.project', verbose_name='关联作品'),
        ),
        migrations.AddConstraint(
            model_name='honor',
            constraint=models.CheckConstraint(condition=models.Q(('importance__lte', 100)), name='honor_importance_range'),
        ),
    ]
