# Generated by Django 5.2.17 on 2026-09-03 07:42

import django.db.models.deletion
import showcase.schema
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.JSONField(default=showcase.schema.empty_design)),
                ('published', models.JSONField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('public_name', models.CharField(blank=True, db_index=True, max_length=30)),
                ('public_tags', models.CharField(blank=True, max_length=60)),
                ('public_cohort', models.CharField(blank=True, db_index=True, max_length=4)),
                ('public_direction', models.CharField(blank=True, db_index=True, max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('moderation_reason', models.CharField(blank=True, max_length=500)),
                ('withdrawal_reason', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '成员展示',
                'verbose_name_plural': '成员展示',
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=12)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to='showcase.showcase')),
            ],
        ),
        migrations.CreateModel(
            name='ShowcaseAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='showcase/')),
                ('thumbnail', models.FileField(upload_to='showcase/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='showcase.showcase')),
            ],
        ),
    ]
