# Generated by Django 5.2.16 on 2026-07-20 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='批次名称')),
                ('intro', models.TextField(blank=True, help_text='展示在报名页顶部：招新对象、流程、时间线、联系方式等', verbose_name='招新说明（Markdown）')),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开放报名时间')),
                ('closes_at', models.DateTimeField(blank=True, help_text='留空表示长期开放', null=True, verbose_name='报名截止时间')),
                ('is_active', models.BooleanField(default=True, help_text='仅启用且在时间窗内的批次会对外开放报名；同一时间建议只启用一个', verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '招新批次',
                'verbose_name_plural': '招新批次',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('hardware', '硬件部'), ('software', '软件部'), ('undecided', '都想试试 / 未定')], default='undecided', max_length=12, verbose_name='意向部门')),
                ('skills', models.CharField(blank=True, max_length=200, verbose_name='特长 / 已掌握技能')),
                ('self_intro', models.TextField(help_text='简单介绍自己、为什么想加入、期待收获什么', verbose_name='自我介绍')),
                ('status', models.CharField(choices=[('submitted', '已报名'), ('first_pass', '一面通过'), ('second_pass', '二面通过'), ('rejected', '未录取')], db_index=True, default='submitted', max_length=12, verbose_name='进展')),
                ('interview_note', models.CharField(blank=True, help_text='仅管理组可见', max_length=300, verbose_name='面试备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='报名人')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.campaign', verbose_name='招新批次')),
            ],
            options={
                'verbose_name': '招新报名',
                'verbose_name_plural': '招新报名',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user'), name='uniq_campaign_application')],
            },
        ),
    ]
