# Generated by Django 5.2.17 on 2026-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_open_2026_autumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_impression',
            field=models.TextField(blank=True, verbose_name='对协会的初步印象'),
        ),
        migrations.AddField(
            model_name='application',
            name='heard_from',
            field=models.JSONField(blank=True, default=list, help_text='Channel 的键数组。多选，允许含 other（补充写在 heard_from_other）', verbose_name='从哪儿知道我们的'),
        ),
        migrations.AddField(
            model_name='application',
            name='heard_from_other',
            field=models.CharField(blank=True, max_length=60, verbose_name='其他渠道'),
        ),
        migrations.AddField(
            model_name='application',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='Interest 的键数组。多选，允许含 other（补充写在 interests_other）', verbose_name='感兴趣的方向'),
        ),
        migrations.AddField(
            model_name='application',
            name='interests_other',
            field=models.CharField(blank=True, max_length=60, verbose_name='其他方向'),
        ),
        migrations.AddField(
            model_name='application',
            name='motto',
            field=models.TextField(blank=True, verbose_name='对大学四年的寄语'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.CharField(blank=True, help_text='做过什么、玩过什么。零基础就写零基础，这一项不筛人', max_length=200, verbose_name='主要经历（电子方面）/ 兴趣爱好'),
        ),
    ]
