# Generated by Django 5.2.16 on 2026-07-12 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('category', models.CharField(choices=[('training', '培训资料'), ('contest', '竞赛资料'), ('tool', '工具软件'), ('other', '其他')], default='training', max_length=20, verbose_name='分类')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '仅会员')], default='public', max_length=20, verbose_name='可见范围')),
                ('file', models.FileField(upload_to='resources/%Y/%m/', verbose_name='文件')),
                ('size', models.BigIntegerField(default=0, editable=False, verbose_name='大小(字节)')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
                'ordering': ['-created_at'],
            },
        ),
    ]
