# Generated by Django 5.2.16 on 2026-07-19 03:37
from django.db import migrations, models


def visibility_to_level(apps, schema_editor):
    """老 visibility=members 的资料 -> 报名会员及以上(1)；public -> 0。"""
    Resource = apps.get_model("files", "Resource")
    Resource.objects.filter(visibility="members").update(min_level=1)


def backwards(apps, schema_editor):
    Resource = apps.get_model("files", "Resource")
    Resource.objects.filter(min_level__gte=1).update(visibility="members")


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='min_level',
            field=models.PositiveSmallIntegerField(choices=[(0, '公开（所有人）'), (1, '报名会员及以上'), (2, '预备会员及以上'), (3, '正式会员及以上'), (4, '干事及以上')], default=0, help_text='达到该等级的成员才能查看和下载', verbose_name='可见等级'),
        ),
        migrations.RunPython(visibility_to_level, backwards),
        migrations.RemoveField(
            model_name='resource',
            name='visibility',
        ),
    ]
