# Generated by Django 5.2.16 on 2026-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='说明文字')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='图片')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='数字小的排前面', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='哈尔滨工程大学电子科技协会', max_length=50, verbose_name='站点名称')),
                ('site_name_en', models.CharField(default='HEU ESTA', max_length=100, verbose_name='英文名称')),
                ('founding_year', models.PositiveIntegerField(default=1995, verbose_name='成立年份')),
                ('recruit_video_bvid', models.CharField(default='BV1AhnGzVEsD', help_text='B 站视频的 BV 号，例如 BV1AhnGzVEsD。换招新视频时改这里即可。', max_length=20, verbose_name='招新视频 BV 号')),
                ('recruit_qq_group', models.CharField(default='1015304209', max_length=20, verbose_name='招新 QQ 群号')),
                ('bilibili_mid', models.CharField(default='70859324', max_length=20, verbose_name='B 站账号 UID')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
