# Generated by Django 5.2.16 on 2026-07-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bilisnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiliSnapshot',
        ),
    ]
