# Generated by Django 5.2.16 on 2026-07-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_bilisnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='auto_approve',
            field=models.BooleanField(default=True, help_text='开启后：注册通过邮箱验证即自动激活，无需管理员手动审核。', verbose_name='注册自动审核'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='beta_mode',
            field=models.BooleanField(default=True, help_text='开启后：全站显示内测反馈入口；新注册用户自动提升为干事以便测试全部功能。', verbose_name='内测模式'),
        ),
    ]
