# Generated by Django 5.2.16 on 2026-07-19 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfig_auto_approve_siteconfig_beta_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, help_text='QQ/邮箱，匿名提交时选填', max_length=100, verbose_name='联系方式')),
                ('page', models.CharField(blank=True, max_length=300, verbose_name='提交页面')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理')], db_index=True, default='pending', max_length=10, verbose_name='状态')),
                ('admin_note', models.CharField(blank=True, max_length=200, verbose_name='处理备注')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_resolved', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '内测反馈',
                'verbose_name_plural': '内测反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
