# Generated by Django 5.2.16 on 2026-07-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='featured_video_bvids',
            field=models.TextField(blank=True, default='', help_text='每行一个 BV 号，最多取前 3 个，作为首页「精选培训视频」展示；留空则自动展示最新 3 个投稿。挑封面干净的视频放这里。', verbose_name='首页精选视频 BV 号'),
        ),
    ]
