# Generated by Django 5.2.17 on 2026-08-26 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_formal_recruitment_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='必须与 core/slots.py 登记表里的 key 完全一致', max_length=80, unique=True, verbose_name='槽位标识')),
                ('image', models.ImageField(height_field='height', upload_to='slots/%Y/%m/', verbose_name='图片', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='宽')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='高')),
                ('alt', models.CharField(blank=True, help_text='给读屏软件描述画面内容。留空则用登记表里的名字，但那通常不够具体。', max_length=200, verbose_name='替代文本')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='图注')),
                ('credit', models.CharField(blank=True, max_length=60, verbose_name='拍摄者')),
                ('focal_x', models.PositiveSmallIntegerField(default=50, verbose_name='焦点横向 %')),
                ('focal_y', models.PositiveSmallIntegerField(default=50, verbose_name='焦点纵向 %')),
                ('is_active', models.BooleanField(default=True, help_text='取消勾选后该位置回到占位状态，图片本身保留', verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_slots_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '素材槽',
                'verbose_name_plural': '素材槽',
                'ordering': ['key'],
            },
        ),
    ]
