# Generated by Django 5.2.17 on 2026-08-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mediaslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaslot',
            name='video_mp4',
            field=models.FileField(blank=True, help_text='H.264 / 720p / 无声。单文件建议不超过 1.5MB。', upload_to='slots/video/%Y/%m/', verbose_name='循环片段 MP4'),
        ),
        migrations.AddField(
            model_name='mediaslot',
            name='video_webm',
            field=models.FileField(blank=True, help_text='VP9，同画质比 MP4 小三成左右。可以不传。', upload_to='slots/video/%Y/%m/', verbose_name='循环片段 WebM'),
        ),
    ]
