# Generated by Django 5.2.16 on 2026-07-20 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='活动名称')),
                ('kind', models.CharField(choices=[('training', '培训'), ('lecture', '讲座'), ('contest', '竞赛宣讲'), ('meeting', '例会'), ('other', '其他')], default='training', max_length=12, verbose_name='类型')),
                ('description', models.TextField(help_text='支持 Markdown：安排、要求、带什么东西等', verbose_name='活动详情（Markdown）')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='地点')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('signup_deadline', models.DateTimeField(blank=True, help_text='留空则报名到活动开始前一刻', null=True, verbose_name='报名截止')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 表示不限', verbose_name='人数上限')),
                ('min_level', models.PositiveSmallIntegerField(choices=[(0, '公开（所有人）'), (1, '报名会员及以上'), (2, '预备会员及以上'), (3, '正式会员及以上'), (4, '干事及以上')], default=0, help_text='达到该等级的成员才能看到并报名', verbose_name='报名等级门槛')),
                ('points_reward', models.PositiveSmallIntegerField(default=5, help_text='成员签到成功后获得的积分，0 表示不给分', verbose_name='签到积分')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('checkin_open', models.BooleanField(default=False, editable=False, verbose_name='签到开放中')),
                ('checkin_code', models.CharField(blank=True, editable=False, max_length=6, verbose_name='签到口令')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_walkin', models.BooleanField(default=False, help_text='未提前报名、现场签到时自动创建', verbose_name='现场参加')),
                ('checkin_at', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('reminded', models.BooleanField(default=False, editable=False, verbose_name='已发开场提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='events.event', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='uniq_event_signup')],
            },
        ),
    ]
