"""Split existing licensed font subsets without dropping any codepoint.
Run after build_fonts.py when copy or font sources change. --check verifies shipped shards.
The small critical set is fixed; home/page groups prevent a few Chinese characters
from pulling in a full alphabet. unicode-range is disjoint within each family/weight.
"""
import argparse
import json
import re
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
from fontTools.ttLib import TTFont
from fontTools.subset import Options, Subsetter

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / 'app/static/fonts'
OUT = FONTS / 'shards'
FACES = [
    ('sans-regular', 'SourceHanSansCN-Regular-subset.woff2', 'ESTA Sans', '400'),
    ('sans-bold', 'SourceHanSansCN-Bold-subset.woff2', 'ESTA Sans', '700'),
    ('display', 'SmileySans-subset.woff2', 'ESTA Display', '100 900'),
    ('serif', 'SourceHanSerifCN-SemiBold-subset.woff2', 'ESTA Serif', '600'),
    ('mono', 'JetBrainsMono-subset.woff2', 'JetBrains Mono', '100 800'),
]
CRITICAL = set(map(ord, '哈尔滨工程大学电子科技协会焊接每一个奇思妙想从制作电路到编写程序在真实项目中一起成长探索查看招新首页指南了解学习资源登录参加我们作品荣誉培训联系硬件软件会员中心返回退出菜单关闭跳过开场')) | set(range(32,127)) | set(map(ord,'，。、：！？·—→（）'))


def visible_chars(path):
    s = path.read_text(encoding='utf-8')
    s = re.sub(r'{%\s*comment\s*%}.*?{%\s*endcomment\s*%}|<!--.*?-->', '', s, flags=re.S)
    s = re.sub(r'{%.*?%}|{{.*?}}|{#.*?#}|<[^>]*>', '', s, flags=re.S)
    return set(map(ord, s))


def ranges(points):
    parts=[]
    for cp in sorted(points):
        if parts and cp == parts[-1][1]+1: parts[-1][1]=cp
        else: parts.append([cp,cp])
    return ','.join('U+%X'%a if a==b else 'U+%X-%X'%(a,b) for a,b in parts)


def cmap(path):
    with TTFont(path) as f: return set(f.getBestCmap())


def build_face(face, home, templates):
    prefix, source, family, weight = face
    covered = cmap(FONTS/source)
    groups=[]; remaining=set(covered)
    for name, pool in [('critical',CRITICAL),('home',home),('pages',templates),('extended',covered)]:
        values=sorted(remaining & pool)
        remaining.difference_update(values)
        chunks=[values] if name=='critical' else [values[i:i+128] for i in range(0,len(values),128)]
        for i, points in enumerate(chunks):
            if not points: continue
            filename=f'{prefix}-{name}'+(f'-{i:02}' if name!='critical' else '')+'.woff2'
            opt=Options(); opt.flavor='woff2'; opt.recalc_timestamp=False; opt.layout_features=['*']; opt.drop_tables += ['FFTM']
            font=TTFont(FONTS/source, recalcTimestamp=False)
            sub=Subsetter(options=opt);sub.populate(unicodes=points);sub.subset(font);font.flavor='woff2'
            font.save(OUT/filename);font.close()
            groups.append({'file':filename,'codepoints':points,'bytes':(OUT/filename).stat().st_size})
    print(prefix, len(groups), 'shards', sum(x['bytes'] for x in groups), 'bytes', flush=True)
    return {'source':source,'family':family,'weight':weight,'shards':groups}


def check():
    data=json.loads((OUT/'manifest.json').read_text(encoding='utf-8'))
    for face in data:
        seen=set()
        for s in face['shards']:
            expected=set(s['codepoints']); actual=cmap(OUT/s['file'])
            assert expected == actual, s['file']+' cmap mismatch'
            assert not (seen & actual), s['file']+' overlaps'
            seen.update(actual)
        assert seen==cmap(FONTS/face['source']), face['source']+' lost glyphs'
    print('PASS: every source codepoint covered exactly once in every font face')


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    if args.check: return check()
    OUT.mkdir(exist_ok=True)
    home=visible_chars(ROOT/'app/templates/core/home.html') | visible_chars(ROOT/'app/templates/base.html')
    templates=set().union(*(visible_chars(p) for p in (ROOT/'app/templates').rglob('*.html')))
    with ThreadPoolExecutor(max_workers=3) as pool:
        data=list(pool.map(lambda f:build_face(f,home,templates),FACES))
    css=['/* Generated by scripts/build_font_shards.py. Full coverage; on-demand transfer. */']
    critical=['/* Critical visible text; remaining glyphs load after the opening. */']
    used=set()
    for face in data:
        for s in face['shards']:
            used.add(s['file'])
            target = critical if '-critical.' in s['file'] else css
            target.append('@font-face { font-family: "%s"; font-style: normal; font-weight: %s; font-display: swap; src: url("../fonts/shards/%s") format("woff2"); unicode-range: %s; }'%(face['family'],face['weight'],s['file'],ranges(s['codepoints'])))
    for path in OUT.glob('*.woff2'):
        if path.name not in used: path.unlink()
    (ROOT/'app/static/css/fonts.css').write_text('\n'.join(css)+'\n',encoding='utf-8')
    (ROOT/'app/static/css/fonts-critical.css').write_text('\n'.join(critical)+'\n',encoding='utf-8')
    (OUT/'manifest.json').write_text(json.dumps(data,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
    check()

if __name__=='__main__':main()
