# Generated by Django 5.2.16 on 2026-07-20 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('level', '等级变更'), ('medal', '勋章授予'), ('feedback', '反馈动态'), ('news', '公告'), ('event', '活动'), ('recruit', '招新'), ('points', '积分'), ('project', '项目'), ('system', '系统')], default='system', max_length=12, verbose_name='类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='内容')),
                ('url', models.CharField(blank=True, help_text='站内相对路径，点击通知后跳转', max_length=300, verbose_name='跳转链接')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notify_noti_user_id_64a3cc_idx')],
            },
        ),
    ]
