# Generated by Django 5.2.16 on 2026-07-20 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='正数加分，负数扣分', verbose_name='分值变化')),
                ('source', models.CharField(choices=[('event', '活动签到'), ('admin', '管理调整')], max_length=10, verbose_name='来源')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('operator', models.ForeignKey(blank=True, help_text='手动调整时的操作人；系统发放为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_ops', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='points_poin_user_id_0aebf1_idx')],
            },
        ),
    ]
