# Generated by Django 5.2.17 on 2026-09-06 12:24

import achievements.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0004_alter_honor_note'),
        ('projects', '0003_member_work_publishing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(blank=True, max_length=60)),
                ('cohort', models.CharField(blank=True, max_length=4)),
                ('active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('honor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='news.honor')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=60)),
                ('role', models.CharField(blank=True, max_length=60)),
                ('evidence', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', '待核验'), ('approved', '已关联'), ('rejected', '未通过'), ('cancelled', '已取消')], default='pending', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_claims', to=settings.AUTH_USER_MODEL)),
                ('honor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.honor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievements.contributor')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HonorDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.JSONField(default=dict)),
                ('published', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('honor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_draft', to='news.honor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=achievements.models.certificate_path)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='achievements.honordraft')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('honor__isnull', True), ('project__isnull', False)), models.Q(('honor__isnull', False), ('project__isnull', True)), _connector='OR'), name='credit_one_record'),
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('user__isnull', False)), fields=('project', 'user'), name='credit_project_user'),
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('user__isnull', False)), fields=('honor', 'user'), name='credit_honor_user'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('honor__isnull', True), ('project__isnull', False)), models.Q(('honor__isnull', False), ('project__isnull', True)), _connector='OR'), name='claim_one_record'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('project', 'applicant'), name='claim_project_applicant'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('honor', 'applicant'), name='claim_honor_applicant'),
        ),
    ]
