# Generated by Django 5.2.17 on 2026-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='from_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributor',
            name='invitation_declined',
            field=models.BooleanField(default=False),
        ),
    ]
