# Generated by Django 5.2.17 on 2026-09-07 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_contributor_from_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_for', models.CharField(blank=True, max_length=64)),
                ('blocked_reason', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('config_hash', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=80)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('result', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='achievements.certificate')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'succeeded'])), fields=('fingerprint',), name='honor_recognition_dedup')],
            },
        ),
    ]
