# Generated by Django 5.2.17 on 2026-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_recognition_gate_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitiongate',
            name='busy_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='recognitiongate',
            name='counters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recognitiongate',
            name='lease',
            field=models.UUIDField(null=True),
        ),
    ]
