# Generated by Django 5.2.16 on 2026-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiliSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('follower', models.PositiveIntegerField(default=0, verbose_name='粉丝数')),
                ('videos', models.PositiveIntegerField(default=0, verbose_name='视频数')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='获赞数')),
            ],
            options={
                'verbose_name': 'B站数据快照',
                'verbose_name_plural': 'B站数据快照',
                'ordering': ['date'],
            },
        ),
    ]
